model_config: configs/model/small_action_only.yaml
run_tag: cube_single_task

lerobot_repo_id: ehalicki/so101_cube_simple

steps: 50000
effective_batch_size: 64
base_batch_size: 64
lr: 7.0e-5
warmup_steps: 200
crop_size: 256
num_workers: 4
save_every: 50
small_dataset: false # runs on lewam_community_dataset_small
resume: null
s3_path: s3://zima-data/lewam/checkpoints
scaled_fps: 3
action_fps: 30
overfit_test: false 
timezone: Europe/Zurich
action_weight: 1.0 # not sure what this should be tbh
lang_drop_rate: 0.15
force_batch_size: null
no_compile: true
