model_config: configs/model/base.yaml
run_tag: vid_only_pretraining

lerobot_repo_id: null
val_fraction: 0.1
val_split_seed: 42
val_batches: 5
val_num_cameras: 2

steps: 50000
effective_batch_size: 128
base_batch_size: 128
lr: 7.0e-5
warmup_steps: 200
crop_size: 256
num_workers: 4
save_every: 50
small_dataset: false # runs on lewam_community_dataset_small
resume: null
s3_path: s3://lewam/checkpoints
scaled_fps: 5
action_fps: 30
overfit_test: false 
timezone: Europe/Zurich
action_weight: 1.0 # not sure what this should be tbh
lang_drop_rate: 0.15
force_batch_size: null
vram_target_fraction: 0.85
no_compile: true
video_only: true
gradient_checkpointing: true
